version: '3.7'

networks:
  nevs_net:
    name: nevs_network

services:
  peer1.central.govt:
    image: hyperledger/fabric-peer:2.5
    container_name: peer1.central.govt
    environment:
      # External Builder config for CCaaS
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.central.govt:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_ID=peer1.central.govt
      - CORE_PEER_ADDRESS=peer1.central.govt:8051
      - CORE_PEER_LOCALMSPID=CentralGovtMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/peer/tls/ca.crt
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.central.govt:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.central.govt:8051
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/central.govt/peers/peer1.central.govt/msp:/var/hyperledger/peer/msp
      - ../organizations/peerOrganizations/central.govt/peers/peer1.central.govt/tls:/var/hyperledger/peer/tls
    ports:
      - "8051:8051"
    networks:
      - nevs_net
